version: 0.2

phases: 
    pre_build:
        commands:
        - echo "Entered the pre_build phases"
    build:
        commands:
        - echo "Entered the build phases"
        - mvn clean install -DskipTests
    post_build:
        commands: 
        - echo "Entered the post_build phases"
artifacts:
    files:
        - '**/*'
    base-directory: 'target/aws-elastic-beanstalk-example-0.0.1-SNAPSHOT'